[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.89.4"

[context.production]
  command = "hugo"

[context.branch-deploy]
  command = "hugo --environment staging"

[[redirects]]
  from = "https://blog.techrelay.xyz"
  to = "https://techrelay.blog"
  status = 200
  force = true
  query = {path = ":path"}
