[[main]]
name = "Home"
url = ""
weight = -110
[[main]]
name = "Archives"
url = "post/rich-content/"
weight = -109
[[main]]
identifier = "Links"
name = "Links"
weight = -108
[[main]]
name = "LinkedIn"
parent = "Links"
url = "https://www.linkedin.com/"
[[main]]
name = "Twitter"
parent = "Links"
url = "https://twitter.com/"
[[main]]
name = "About"
url = "about/"
weight = -107
[[main]]
name = "Contribute"
url = "post/contribute/"
[[main]]
name = "Contact"
url = "post/contact/"
weight = ""
[[social]]
name = "github"
type = "social"
url = "https://github.com/techrelay"
weight = 1
[[social]]
name = "twitter"
url = "https://twitter.com/techrelay"
weight = 2
[[social]]
name = "linkedin"
url = "https://www.linkedin.com/in/#"
weight = 3
[[social]]
name = "rss"
url = "index.xml"
weight = 4
